# Generated by Django 6.0.5 on 2026-05-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="medicine",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="category",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="pharmacy",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="medicine",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="pharmacy",
        ),
        migrations.RemoveField(
            model_name="pharmacy",
            name="user",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Medicine",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="Pharmacy",
        ),
    ]
