# Generated by Django 6.0.5 on 2026-05-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
