# Generated by Django 6.0.5 on 2026-05-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0008_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash on Delivery"),
                    ("GPAY", "Google Pay"),
                    ("PHONEPE", "PhonePe"),
                    ("CARD", "Credit/Debit Card"),
                    ("RAZORPAY", "Razorpay"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
    ]
