# Generated by Django 6.0.5 on 2026-05-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0009_order_razorpay_order_id_order_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="prescription",
            field=models.ImageField(blank=True, null=True, upload_to="prescriptions/"),
        ),
    ]
